# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FFt0Xr4ILwXpSLPM37Dbtx94GmrqTqc7
"""

"""
Stage: Development-01
@author: Deniz Kuzey,119202077
@author: Zafer Sercan Yıldız, 119202037
@author: Hacı Mesut Eren Götürmen, 120202094
"""
import requests
from bs4 import BeautifulSoup
url ='https://www.imdb.com/chart/top/'

page = requests.get(url)

soup = BeautifulSoup(page.content, "html.parser")

mov_name_rating_dict = dict()
mov_names = []
mov_ratings = []

mov_i = 1
rating_i = 1

for movie_name in soup.find_all('td',attrs={'class':'titleColumn'}):
    mov_names.append(movie_name.get_text().strip()) 

for imdb_rating in soup.find_all('td',attrs={'class':'ratingColumn imdbRating'}):
    mov_ratings.append(imdb_rating.get_text().strip())


for i in range(1,len(mov_names)):
    print("Movie Name:",mov_names[i], "\n IMDB Rating:",mov_ratings[i],sep="")
    print('--------')